version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/android/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/function/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
    # By default, Flutter repository is determined as a library and only version
    # constraint updates are made, so change the versioning strategy.
    # See https://github.com/dependabot/dependabot-core/issues/4979
    versioning-strategy: "increase"
