version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    ignore:
      - dependency-name: "google-github-actions/deploy-cloud-functions"
        # For functions v1, ignore all updates greater than or equal to version 3
        versions: ">= 3"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "gradle"
    directory: "/android/"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pip"
    directory: "/function/"
    open-pull-requests-limit: 1
    reviewers:
      - "shotaIDE"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
