version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "03:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "gradle"
    directory: "/android/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "05:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pip"
    directory: "/function/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Tokyo"
  - package-ecosystem: "pub"
    directory: "/"
    open-pull-requests-limit: 1
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Asia/Tokyo"
    # By default, Flutter repository is determined as a library and only version
    # constraint updates are made, so change the versioning strategy.
    # See https://github.com/dependabot/dependabot-core/issues/4979
    versioning-strategy: "increase"
