include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/firebase_options*.dart"
    - "lib/generated_plugin_registrant.dart"

linter:
  rules:
    avoid_catches_without_on_clauses: false
