include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - dart_code_metrics
  exclude:
    - "build/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/firebase_options.dart"
    - "lib/generated_plugin_registrant.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - always_use_package_imports
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catching_errors
    - avoid_double_and_int_checks
    - avoid_dynamic_calls
    - avoid_escaping_inner_quotes
    - avoid_field_initializers_in_const_classes
    - avoid_implementing_value_types
    - avoid_js_rounded_ints
    - avoid_multiple_declarations_per_line
    - avoid_positional_boolean_parameters
    - avoid_private_typedef_functions
    - avoid_redundant_argument_values
    - avoid_returning_null
    - avoid_returning_this
    - avoid_setters_without_getters
    - avoid_slow_async_io
    - avoid_type_to_string
    - avoid_types_on_closure_parameters
    - avoid_unused_constructor_parameters
    - avoid_void_async
    - cancel_subscriptions
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - close_sinks
    - comment_references
    - deprecated_consistency
    - directives_ordering
    - flutter_style_todos
    - invariant_booleans
    - join_return_with_assignment
    - lines_longer_than_80_chars
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - no_default_cases
    - noop_primitive_operations
    - omit_local_variable_types
    - only_throw_errors
    - package_api_docs
    - parameter_assignments
    - prefer_asserts_in_initializer_lists
    - prefer_constructors_over_static_methods
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_foreach
    - prefer_if_elements_to_conditional_expressions
    - prefer_int_literals
    - prefer_single_quotes
    - require_trailing_commas
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - test_types_in_equals
    - throw_in_finally
    - tighten_type_of_initializing_formals
    - type_annotate_public_apis
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_checks
    - unnecessary_parenthesis
    - unnecessary_raw_strings
    - unnecessary_statements
    - unsafe_html
    - use_is_even_rather_than_modulo
    - use_late_for_private_fields_and_variables
    - use_named_constants
    - use_setters_to_change_properties
    - use_string_buffers
    - use_to_and_as_if_applicable

dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
    maintainability-index: 50
  rules:
    - avoid-global-state
    - avoid-nested-conditional-expressions:
        acceptable-level: 1
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-assertions
    - avoid-unnecessary-type-casts
    - avoid-unrelated-type-assertions
    - avoid-unused-parameters
    - binary-expression-operand-order
    - member-ordering-extended:
        order:
          - constructors
          - public-static-const-fields
          - public-static-final-fields
          - public-static-var-fields
          - private-static-const-fields
          - private-static-final-fields
          - private-static-var-fields
          - public-fields
          - private-fields
          - public-getters
          - private-getters
          - public-setters
          - private-setters
          - public-static-methods
          - private-static-methods
          - overridden-methods
          - public-methods
          - private-methods
    - no-boolean-literal-compare
    - no-equal-then-else
    # - no-magic-number
    - no-object-declaration
    - prefer-first
    - prefer-last
    - prefer-match-file-name
    - avoid-wrapping-in-padding
  rules-exclude:
    - prefer-conditional-expressions
