include: package:colomney_lints/analysis_options.yaml

analyzer:
  exclude:
    - "build/**"
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "lib/firebase_options*.dart"
    - "lib/generated_plugin_registrant.dart"
