environment_config:
  path: environment_config.dart

  fields:
    twitterApiKey:
      type: String
      env_var: TWITTER_API_KEY
    twitterApiKeySecret:
      type: String
      env_var: TWITTER_API_KEY_SECRET
    twitterRedirectUri:
      type: String
      env_var: TWITTER_REDIRECT_URI
