name: meow_music
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  rxdart: ^0.27.3
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  file_picker: ^4.3.3
  path: ^1.8.0
  collection: ^1.15.0
  audioplayers: ^0.20.1
  share_plus: ^4.0.4
  path_provider: ^2.0.9
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^9.4.0
  url_launcher: ^6.0.20
  ffmpeg_kit_flutter: 4.5.1-LTS
  skeletons: ^0.0.3
  video_trimmer: ^0.6.0
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  dart_code_metrics: ^4.10.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
