name: my_pet_melody
description: A new Flutter project.

publish_to: "none"

version: 1.0.24+54

environment:
  sdk: ">=2.16.0 <3.0.0"
  # Specify for inference of dependabot
  flutter: ">=3.19.3"

dependencies:
  audioplayers: 5.2.1
  chewie: 1.7.5
  cloud_firestore: 4.14.0
  collection: 1.18.0
  cross_file: 0.3.3+4
  cupertino_icons: 1.0.6
  device_info_plus: 9.1.2
  dio: 5.4.1
  ffmpeg_kit_flutter: 5.1.0-LTS
  file_picker: 6.2.0
  firebase_analytics: 10.8.6
  firebase_auth: 4.16.0
  firebase_core: 2.25.4
  firebase_crashlytics: 3.4.15
  firebase_messaging: 14.7.15
  firebase_remote_config: 4.3.13
  firebase_storage: 11.6.5
  flutter:
    sdk: flutter
  flutter_local_notifications: 16.3.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10+1
  font_awesome_flutter: 10.7.0
  freezed_annotation: 2.4.1
  google_sign_in: 6.2.1
  in_app_review: 2.0.9
  intl: 0.19.0
  package_info_plus: 5.0.1
  path: 1.9.0
  path_provider: 2.1.2
  purchases_flutter: 6.19.0
  rxdart: 0.27.7
  share_plus: 7.2.2
  shared_preferences: 2.2.2
  skeletons: 0.0.3
  twitter_login: 4.4.2
  url_launcher: 6.2.5
  video_player: 2.8.3
  video_thumbnail: 0.5.3
  video_trimmer: 2.1.0

dev_dependencies:
  build_runner: 2.4.8
  cider: 0.2.7
  flutter_test:
    sdk: flutter
  freezed: 2.4.7
  json_serializable: 6.7.1
  mocktail: 1.0.3
  pedantic_mono: 1.25.0
  watcher: 1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
