name: my_pet_melody
description: A new Flutter project.

publish_to: "none"

version: 1.0.24+54

environment:
  sdk: ">=2.16.0 <3.0.0"
  # Specify for inference of dependabot
  flutter: ">=3.19.5"

dependencies:
  audioplayers: 6.0.0
  chewie: 1.8.1
  cloud_firestore: 4.16.0
  collection: 1.18.0
  cross_file: 0.3.4+1
  cupertino_icons: 1.0.6
  device_info_plus: 10.0.1
  dio: 5.4.2
  ffmpeg_kit_flutter: 6.0.3
  file_picker: 8.0.0+1
  firebase_analytics: 10.10.0
  firebase_auth: 4.19.0
  firebase_core: 2.28.0
  firebase_crashlytics: 3.5.0
  firebase_messaging: 14.7.21
  firebase_remote_config: 4.3.19
  firebase_storage: 11.6.11
  flutter:
    sdk: flutter
  flutter_local_notifications: 17.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10+1
  font_awesome_flutter: 10.7.0
  freezed_annotation: 2.4.1
  google_sign_in: 6.2.1
  in_app_review: 2.0.9
  intl: 0.18.1
  package_info_plus: 6.0.0
  path: 1.9.0
  path_provider: 2.1.2
  purchases_flutter: 6.24.0
  rxdart: 0.27.7
  share_plus: 8.0.2
  shared_preferences: 2.2.2
  skeletons: 0.0.3
  twitter_login: 4.4.2
  url_launcher: 6.2.5
  video_player: 2.8.5
  video_thumbnail: 0.5.3
  video_trimmer: 3.0.1

dev_dependencies:
  build_runner: 2.4.9
  cider: 0.2.7
  flutter_test:
    sdk: flutter
  freezed: 2.5.0
  json_serializable: 6.7.1
  mocktail: 1.0.3
  pedantic_mono: 1.26.0
  watcher: 1.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
