name: meow_music
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^1.1.0
  rxdart: ^0.27.3
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.13
  dio: ^4.0.4
  file_picker: ^4.3.3
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  dart_code_metrics: ^4.10.1
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
