name: meow_music
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.0.3
  rxdart: ^0.27.3
  flutter_riverpod: ^2.1.3
  intl: ^0.17.0
  introduction_screen: ^3.1.2
  shared_preferences: ^2.0.20
  dio: ^4.0.4
  file_picker: ^5.2.6
  path: ^1.8.0
  collection: ^1.15.0
  audioplayers: ^3.0.1
  share_plus: ^6.3.1
  path_provider: ^2.0.9
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.6
  flutter_local_notifications: ^13.0.0
  url_launcher: ^6.1.10
  ffmpeg_kit_flutter: 4.5.1-LTS
  skeletons: ^0.0.3
  video_trimmer: ^1.1.3
  firebase_storage: ^10.2.16
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.16
  chewie: ^1.4.0
  video_player: ^2.4.10
  cross_file: ^0.3.3+2
  video_thumbnail: ^0.5.3
  video_compress: ^3.1.2

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  colomney_lints:
    git:
      url: https://github.com/shotaIDE/ColomneyFlutterLints.git
      ref: main

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
