name: my_pet_melody
description: A new Flutter project.

publish_to: "none"

version: 1.0.24+54

environment:
  sdk: "3.3.4"
  # Specify for inference of dependabot
  flutter: 3.19.6

dependencies:
  audioplayers: 6.0.0
  chewie: 1.8.1
  cloud_firestore: 5.0.0
  collection: 1.18.0
  cross_file: 0.3.4+1
  cupertino_icons: 1.0.8
  device_info_plus: 10.1.0
  dio: 5.4.3
  ffmpeg_kit_flutter: 6.0.3
  file_picker: 8.0.3
  firebase_analytics: 11.0.0
  firebase_auth: 5.0.0
  firebase_core: 3.0.0
  firebase_crashlytics: 4.0.0
  firebase_messaging: 15.0.0
  firebase_remote_config: 5.0.0
  firebase_storage: 12.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: 17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: 2.5.1
  flutter_svg: 2.0.10+1
  font_awesome_flutter: 10.7.0
  freezed_annotation: 2.4.1
  google_sign_in: 6.2.1
  in_app_review: 2.0.9
  intl: 0.18.1
  package_info_plus: 8.0.0
  path: 1.9.0
  path_provider: 2.1.3
  purchases_flutter: 6.29.3
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.2.3
  skeletons: 0.0.3
  twitter_login: 4.4.2
  url_launcher: 6.3.0
  video_player: 2.8.6
  video_thumbnail: 0.5.3
  video_trimmer: 3.0.1

dev_dependencies:
  build_runner: 2.4.9
  cider: 0.2.7
  flutter_test:
    sdk: flutter
  freezed: 2.5.2
  json_serializable: 6.8.0
  mocktail: 1.0.3
  pedantic_mono: 1.26.0
  watcher: 1.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/icon/
  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
