name: meow_music
description: A new Flutter project.

publish_to: "none"

version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  rxdart: ^0.27.7
  flutter_riverpod: ^2.3.4
  intl: ^0.17.0
  shared_preferences: ^2.1.0
  dio: ^5.1.1
  file_picker: ^5.2.9
  path: ^1.8.2
  collection: ^1.17.0
  audioplayers: ^4.0.1
  share_plus: ^6.3.2
  path_provider: ^2.0.14
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  flutter_local_notifications: ^13.0.0
  url_launcher: ^6.1.10
  ffmpeg_kit_flutter: ^5.1.0
  skeletons: ^0.0.3
  video_trimmer: ^2.0.1
  firebase_storage: ^11.1.0
  firebase_auth: ^4.4.1
  cloud_firestore: ^4.5.1
  chewie: ^1.4.0
  video_player: ^2.6.1
  cross_file: ^0.3.3+4
  video_thumbnail: ^0.5.3
  twitter_login: ^4.3.1
  app_review: ^2.1.2+1
  package_info_plus: ^1.4.3+1

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  colomney_lints:
    git:
      url: https://github.com/shotaIDE/ColomneyFlutterLints.git
      ref: main
  environment_config: ^3.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: uzura
      fonts:
        - asset: fonts/uzura.ttf
