inputs:
  sample-videos-zip-url:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download samples videos
      shell: bash
      working-directory: function
      run: |
        mkdir samples
        cd samples
        curl "${{ inputs.sample-videos-zip-url }}" -o samples.zip
        unzip samples.zip
