inputs:
  sample-movies-zip-url:
    required: true

runs:
  using: "composite"
  steps:
    - name: Download samples videos
      shell: bash
      working-directory: function
      run: |
        mkdir samples
        cd samples
        wget -O samples.zip "${{ inputs.sample-movies-zip-url }}"
        unzip samples.zip
