runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
