runs:
  using: "composite"
  steps:
    - name: Cache CocoaPods
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-
