inputs:
  flutter_version:
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Flutter
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ inputs.flutter_version }}

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter_version }}
