runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
      with:
        distribution: "temurin"
        java-version: "17"

    # Read Flutter version from version file for asdf,
    # remove the "-stable" suffix,
    # and store it in the environment variable
    - name: Get Flutter version
      id: get-flutter-version
      shell: bash
      run: |
        asdf_flutter_version="$(cat .tool-versions | awk '{print $2}')"
        flutter_version="$(echo $asdf_flutter_version | sed -e 's/-stable//g')"
        echo "flutter-version=$flutter_version" >> $GITHUB_OUTPUT

    - name: Cache Flutter on Linux
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      if: startsWith(runner.os, 'Linux')
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}

    - name: Cache Flutter on macOS
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
      if: startsWith(runner.os, 'macOS')
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.OS }}-flutter-${{ steps.get-flutter-version.outputs.flutter-version }}

    - uses: subosito/flutter-action@44ac965b96f18d999802d4b807e3256d5a3f9fa1 # v2
      with:
        flutter-version: ${{ steps.get-flutter-version.outputs.flutter-version }}
