runs:
  using: "composite"
  steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
    - name: Cache Terraform Plugins
      uses: actions/cache@v4
      with:
        path: ~/infra/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-
    - name: Terraform Init
      working-directory: infra
      shell: bash
      run: terraform init
