inputs:
  firebase-options-dart-base64-emulator:
    required: true
  firebase-options-dart-base64-dev:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Flutter
      uses: ./.github/actions/setup-flutter

    - name: Setup Gradle
      uses: ./.github/actions/setup-gradle

    - name: Generate Firebase options files
      uses: ./.github/actions/generate-firebase-options-files
      with:
        firebase-options-dart-base64-emulator: ${{ inputs.firebase-options-dart-base64-emulator }}
        firebase-options-dart-base64-dev: ${{ inputs.firebase-options-dart-base64-dev }}

    - name: Generate key store
      uses: ./.github/actions/generate-key-store

    - name: Android build
      shell: bash
      run: flutter build appbundle --dart-define FLAVOR=dev
