inputs:
  firebase_options_dart_base64_emulator:
    required: true
  firebase_options_dart_base64_dev:
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: ./.github/actions/setup-java

    - name: Get Flutter version
      id: get-flutter-version
      uses: ./.github/actions/get-flutter-version

    - name: Setup Flutter
      uses: ./.github/actions/setup-flutter
      with:
        flutter_version: ${{ steps.get-flutter-version.flutter-version }}

    - name: Generate uncommited files
      uses: ./.github/actions/generate-uncommited-files
      with:
        firebase_options_dart_base64_emulator: ${{ inputs.firebase_options_dart_base64_emulator }}
        firebase_options_dart_base64_dev: ${{ inputs.firebase_options_dart_base64_dev }}

    - name: Cache Gradle
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Android build
      shell: bash
      run: flutter build appbundle --dart-define FLAVOR=dev
