name: CD/Android-Develop

on:
  push:
    tags:
      - "beta/*"
  workflow_dispatch:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter

      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby

      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle

      - name: Generate Firebase options files
        uses: ./.github/actions/generate-firebase-options-files
        with:
          firebase-options-dart-base64-emulator: ${{ inputs.firebase-options-dart-base64-emulator }}
          firebase-options-dart-base64-dev: ${{ inputs.firebase-options-dart-base64-dev }}

      - name: Generate key store
        uses: ./.github/actions/generate-key-store
        with:
          keystore-jks-base64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          store-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}

      - name: Generate Firebase App Distribution service account key file
        run: echo "${{ secrets.FIREBASE_APP_DISTRIBUTION_SERVICE_ACCOUNT_KEY_JSON_BASE64_DEV }}" | base64 -d > fastlane/firebase-app-distribution-develop.json

      - name: Deploy dev app to Firebase App Distribution
        run: bundle exec fastlane android deploy_dev
