name: CD / API Production

on:
  push:
    tags:
      - "function/release/*"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: function
    steps:
      - uses: actions/checkout@v4
      - name: Generate env YAML file
        run: echo "${{ secrets.FUNCTIONS_ENV_YAML_BASE64_PROD }}" | base64 -d > .env.prod.yaml
      - name: Generate Firebase service account key JSON file
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64_PROD }}" | base64 -d > firebase-serviceAccountKey_prod.json
      - name: Generate Cloud Tasks service account key JSON file
        run: echo "${{ secrets.CLOUD_TASKS_SERVICE_ACCOUNT_KEY_JSON_BASE64_PROD }}" | base64 -d > cloud-tasks-serviceAccountKey_prod.json
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: 'auth'
        with:
          service_account: ${{ secrets.DEPLOY_FUNCTIONS_SERVICE_ACCOUNT_EMAIL_PROD }}
          workload_identity_provider: ${{ secrets.DEPLOY_FUNCTIONS_WORKLOAD_IDENTITY_PROVIDER_PROD }}
      - name: Deploy detect Functions to Google Cloud
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: 'detect'
          runtime: 'python310'
          memory_mb: 2048
          region: 'asia-east1'
          env_vars_file: 'function/.env.prod.yaml'
          source_dir: 'function'
          project_id: 'colomney-my-pet-melody'
          min_instances: 0
          max_instances: 1
          deploy_timeout: 600
      - name: Deploy submit Functions to Google Cloud
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: 'submit'
          runtime: 'python310'
          memory_mb: 1024
          region: 'asia-east1'
          env_vars_file: 'function/.env.prod.yaml'
          source_dir: 'function'
          project_id: 'colomney-my-pet-melody'
          min_instances: 0
          max_instances: 1
          deploy_timeout: 600
      - name: Deploy piece Functions to Google Cloud
        uses: google-github-actions/deploy-cloud-functions@v3
        with:
          name: 'piece'
          runtime: 'python310'
          memory_mb: 1024
          region: 'asia-east1'
          env_vars_file: 'function/.env.prod.yaml'
          source_dir: 'function'
          project_id: 'colomney-my-pet-melody'
          min_instances: 0
          max_instances: 1
          deploy_timeout: 600
