name: CD / Regular release

on:
  schedule:
    - cron:  "0 9 28 * *" # 13:00 JST on the 28th day of every month
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  e2e-test-android:
    name: E2E test Android app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Gradle
        uses: ./.github/actions/setup-gradle
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
      - name: Generate uncommited Flutter files
        uses: ./.github/actions/generate-uncommited-flutter-files
        with:
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
      - name: Generate uncommited Flutter files for dev
        uses: ./.github/actions/generate-uncommited-flutter-files-dev
        with:
          dart-defines-json-base64-dev: ${{ secrets.DART_DEFINES_JSON_BASE64_DEV }}
      - name: Generate uncommited Android files for dev
        uses: ./.github/actions/generate-uncommited-android-files-dev
        with:
          google-service-json-base64-dev: ${{ secrets.GOOGLE_SERVICE_JSON_BASE64_DEV }}
      - name: Generate key store
        uses: ./.github/actions/generate-key-store
        with:
          keystore-jks-base64: ${{ secrets.KEYSTORE_JKS_BASE64 }}
          store-password: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
          key-password: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          key-alias: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      - name: Generate automatic codes
        run: bundle exec fastlane generate
      - name: Generate E2E media files
        uses: ./.github/actions/generate-e2e-media-files
        with:
          sample-videos-zip-url: ${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}
      - name: Build Android dev app
        run: flutter build apk --dart-define-from-file 'dart-defines_dev.json'
      - uses: mobile-dev-inc/action-maestro-cloud@v1.8.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: 'build/app/outputs/flutter-apk/app-release.apk'
          android-api-level: 33
          device-locale: ja_JP
          env: |
            APP_ID_SUFFIX=.dev
  trigger-cd-production:
    name: Trigger CD production
    runs-on: ubuntu-latest
    needs: e2e-test-android
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.COLOMNEY_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.COLOMNEY_WORKFLOW_APP_PRIVATE_KEY_PEM }}
      - uses: actions/checkout@v4
        with:
          # Use App tokens instead of default token `GITHUB_TOKEN`
          # to ensure that GitHub Actions will be triggered again after push back.
          token: ${{ steps.generate-token.outputs.token }}
      - name: Setup Git
        uses: ./.github/actions/setup-git
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
      - name: Install Flutter dependencies
        run: bundle exec fastlane install_flutter_dependencies
      - name: Bump patch version
        run: bundle exec fastlane bump_patch_version
      - name: Commit
        run: |
          git add pubspec.yaml
          full_version_name="$(dart run cider version)"
          git commit -m "${full_version_name}"
      - name: Add tag
        run: bundle exec fastlane add_release_candidate_tag
      - name: Push back
        run: git push origin HEAD:${{ github.head_ref }} --tags
