name: CD / Regular release for infrastructure Develop

on:
  schedule:
    - cron: '0 23 * * *' # 08:00 JST every day
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
      - name: Generate Firebase service account key JSON file
        working-directory: function
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64_DEV }}" | base64 -d > firebase-serviceAccountKey_dev.json
      - name: Generate Cloud Tasks service account key JSON file
        working-directory: function
        run: echo "${{ secrets.CLOUD_TASKS_SERVICE_ACCOUNT_KEY_JSON_BASE64_DEV }}" | base64 -d > cloud-tasks-serviceAccountKey_dev.json
      - name: Generate Terraform vars file
        working-directory: infra
        run: echo "${{ secrets.TERRAFORM_VARS_BASE64_DEV }}" | base64 -d > terraform.tfvars
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        id: "auth"
        with:
          service_account: ${{ secrets.DEPLOY_FUNCTIONS_SERVICE_ACCOUNT_EMAIL_DEV }}
          workload_identity_provider: ${{ secrets.DEPLOY_FUNCTIONS_WORKLOAD_IDENTITY_PROVIDER_DEV }}
      - name: Terraform Plan
        working-directory: infra
        run: terraform plan
      - name: Terraform Apply
        working-directory: infra
        run: terraform apply -auto-approve -input=false
