name: CI/Android(dependabot)

on:
  pull_request_target:
    branches: [main]

env:
  JAVA_VERSION: "12.x"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v2

      - name: Build Android
        uses: ./.github/actions/build-android
        with:
          firebase_options_dart_base64_emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase_options_dart_base64_dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
