name: CI/Flutter

on:
  push:
    branches:
      - "feature/**"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Install Code Spell Checker
        run: npm install -g cspell

      # 自動生成ファイルはスペルチェックする必要がないので、チェックアウトした直後に実施
      - name: Check Code Spell
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cspell '**/*.{dart,swift,kt}' | reviewdog -efm="%f:%l:%c - %m" -name='Code Spell Checker' -reporter='github-pr-review'
