name: CI/Flutter(dependabot)

on:
  pull_request_target:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    name: Lint and test Flutter
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Specify PR head commit
          # because the difference may not be reflected on the default merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Lint and test Flutter
        uses: ./.github/actions/lint-and-test-flutter
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          env-base64: ${{ secrets.ENV_BASE64 }}
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
          firebase-options-dart-base64-prod: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_PROD }}
