name: CI/iOS(dependabot)

on:
  pull_request_target:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build iOS app
    runs-on: macos-12
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
      - uses: actions/checkout@v3
        with:
          # Specify PR head commit
          # because the difference may not be reflected on the default merge commit
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build iOS
        uses: ./.github/actions/build-ios
        with:
          env-base64: ${{ secrets.ENV_BASE64 }}
          firebase-options-dart-base64-emulator: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_EMULATOR }}
          firebase-options-dart-base64-dev: ${{ secrets.FIREBASE_OPTIONS_DART_BASE64_DEV }}
