name: CI / API

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  check-impact:
    name: Check impact for API
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@d6e91a2266cdb9d62096cebf1e8546899c6aa18f # v45
        with:
          files: "function/**"
  test:
    name: Test API
    needs: check-impact
    if: needs.check-impact.outputs.has-changed-related-files == 'true'
    # Use the same version to the production runtime.
    # https://cloud.google.com/functions/docs/runtime-support?hl=ja#python
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: function
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        # Use the nearest version of FFMpeg installed in the environment
        # on which the production runtime is based.
        # https://cloud.google.com/functions/docs/reference/system-packages#ubuntu_2204
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg=7:4.4.2-0ubuntu0.22.04.1
      - name: Get Python version
        id: get-python-version
        run: |
          python_version="$(cat .python-version)"
          echo "python-version=$python_version" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: ${{ steps.get-python-version.outputs.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --ignore-installed -r requirements.txt
      - name: Download samples videos
        uses: ./.github/actions/download-sample-videos
        with:
          sample-videos-zip-url: ${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}
      - name: Test
        run: pytest
