name: CI / API

on:
  pull_request:
    branches:
      - "main"
    paths:
      - "task/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    name: Test API
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: task
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        # Use the nearest version of FFMpeg installed in the environment
        # on which the production runtime is based.
        # https://cloud.google.com/functions/docs/reference/system-packages#ubuntu_2204
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg=7:4.4.2-0ubuntu0.22.04.1
      - name: Get Python version
        id: get-python-version
        run: |
          python_version="$(cat .python-version)"
          echo "python-version=$python_version" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ steps.get-python-version.outputs.python-version }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --ignore-installed -r requirements.txt
      - name: Download test samples
        run: |
          mkdir samples
          cd samples
          wget -O samples.zip "${{ secrets.API_TEST_SAMPLE_MOVIES_ZIP_URL }}"
          unzip samples.zip
      - name: Test
        run: pytest
