name: CI / dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  push-back-diff:
    name: Push back diff after building
    runs-on: ubuntu-latest
    # if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'pub')
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Git
        uses: ./.github/actions/setup-git
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
      - name: Install Flutter dependencies
        run: bundle exec fastlane install_flutter_dependencies
      - name: Commit
        run: |
          git pull origin main
          git checkout main pubspec.yaml
          git add pubspec.lock
          git commit --allow-empty -m 'build: fix pubspec.yaml and pubspec.lock'
      - name: Push back
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git push origin "$BRANCH_NAME"
