name: CI / dependabot

on:
  pull_request:
    types:
      - opened
      - synchronize
      - labeled

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  push-back-diffs-if-needed:
    name: Push back diffs after resolving Flutter dependencies if needed
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dart')
    steps:
      - name: Generate token
        id: generate-token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        with:
          app_id: ${{ secrets.COLOMNEY_WORKFLOW_APP_ID }}
          private_key: ${{ secrets.COLOMNEY_WORKFLOW_APP_PRIVATE_KEY_PEM }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.head_ref }}
          # Use App tokens instead of default token `GITHUB_TOKEN`
          # to ensure that GitHub Actions will be triggered again after push back.
          token: ${{ steps.generate-token.outputs.token }}
          fetch-depth: 0
      - name: Setup Git
        uses: ./.github/actions/setup-git
      - name: Setup Flutter
        uses: ./.github/actions/setup-flutter
      - name: Setup Ruby
        uses: ./.github/actions/setup-ruby
      # Workaround for the problem that dependabot writes version constraints 
      # in `pubspec.yaml` and next version update will not work.
      - name: Revert pubspec.yaml
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git checkout main
          git switch "$BRANCH_NAME"
          git checkout main pubspec.yaml
      - name: Install Flutter dependencies
        run: bundle exec fastlane install_flutter_dependencies
      - name: Commit
        run: |
          git add pubspec.yaml pubspec.lock
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'build: fix pubspec.yaml and pubspec.lock'
          fi
      - name: Push back if needed
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          git push origin "$BRANCH_NAME"
