name: CI / Infrastructure Production

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "use-terraform-lock-prod"

jobs:
  check-impact:
    name: Check impact for Terraform
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@c65cd883420fd2eb864698a825fc4162dd94482c # v44
        with:
          files: |
            function/**
            infra/**
            firestore.rules
            storage.rules
  check-plan:
    name: Check Terraform plan
    needs: check-impact
    if: needs.check-impact.outputs.has-changed-related-files == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          service-account-email: ${{ secrets.DEPLOY_FUNCTIONS_SERVICE_ACCOUNT_EMAIL_PROD }}
          workload-identity-provider: ${{ secrets.DEPLOY_FUNCTIONS_WORKLOAD_IDENTITY_PROVIDER_PROD }}
          tfbackend-file-name: "prod.tfbackend"
      - name: Setup tfcmt
        uses: ./.github/actions/setup-tfcmt
      - name: Generate uncommited function files for prod
        uses: ./.github/actions/generate-uncommited-function-files-prod
        with:
          firebase-service-account-key-json-base64-prod: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64_PROD }}
          cloud-tasks-service-account-key-json-base64-prod: ${{ secrets.CLOUD_TASKS_SERVICE_ACCOUNT_KEY_JSON_BASE64_PROD }}
      - name: Generate Terraform vars file
        uses: ./.github/actions/generate-terraform-vars-file
        with:
          terraform-vars-base64: ${{ secrets.TERRAFORM_VARS_BASE64_PROD }}
      - name: Terraform Plan
        working-directory: infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -- terraform plan
  check-plan-no-need:
    name: Check Terraform plan (no need)
    needs: check-impact
    if: needs.check-impact.outputs.has-changed-related-files == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "No changes in files related to Terraform, skipping."
