name: CI / Infrastructure Develop

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "use-terraform-lock"

jobs:
  check-impact:
    name: Check impact for Terraform
    runs-on: ubuntu-latest
    outputs:
      has-changed-related-files: ${{ steps.check-related-files.outputs.any_changed == 'true' }}
    steps:
      - uses: actions/checkout@v4
      - name: Check related files
        id: check-related-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            function/**
            infra/**
            firestore.rules
            storage.rules
  check-plan:
    name: Check Terraform plan
    needs: check-impact
    if: needs.check-impact.outputs.has-changed-related-files == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: ./.github/actions/setup-terraform
        with:
          service-account-email: ${{ secrets.DEPLOY_FUNCTIONS_SERVICE_ACCOUNT_EMAIL_DEV }}
          workload-identity-provider: ${{ secrets.DEPLOY_FUNCTIONS_WORKLOAD_IDENTITY_PROVIDER_DEV }}
          tfbackend-file-name: "dev.tfbackend"
      - name: Setup tfcmt
        env:
          TFCMT_VERSION: v4.10.0
        run: |
          wget "https://github.com/suzuki-shunsuke/tfcmt/releases/download/${TFCMT_VERSION}/tfcmt_linux_amd64.tar.gz" -O /tmp/tfcmt.tar.gz
          tar xzf /tmp/tfcmt.tar.gz -C /tmp
          mv /tmp/tfcmt /usr/local/bin
          tfcmt --version
      - name: Generate uncommited function files for dev
        uses: ./.github/actions/generate-uncommited-function-files-dev
        with:
          firebase-service-account-key-json-base64-dev: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_JSON_BASE64_DEV }}
          cloud-tasks-service-account-key-json-base64-dev: ${{ secrets.CLOUD_TASKS_SERVICE_ACCOUNT_KEY_JSON_BASE64_DEV }}
      - name: Generate Terraform vars file
        uses: ./.github/actions/generate-terraform-vars-file-dev
        with:
          terraform-vars-base64-dev: ${{ secrets.TERRAFORM_VARS_BASE64_DEV }}
      - name: Terraform Plan
        working-directory: infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: tfcmt plan -- terraform plan -var-file=dev.tfvars
  check-plan-no-need:
    name: Check Terraform plan (no need)
    needs: check-impact
    if: needs.check-impact.outputs.has-changed-related-files == 'false'
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: echo "No changes in files related to Terraform, skipping."
